### ISSUE TITLE
Fail downloading some files.  EDIT Duplicate

### ISSUE THREAD

**Issue by ingsbr00** [marklieberman/downloadstar#12]
Example:
If you want to download the "Archives" filter in this page:

https://areaprivada.gasnaturalfenosa.es/ovh-web/downloadLotsInvoices.gas?email=acapelo@ahorroenergeticomunicipal.com&token=b9f0eafb08c63d85dfea8fb18c2bb663fe172d9a17d00650b805386cb3fb6ac5&lang=es&utm_source=AREA%20CLIENTE%20-%20Env%C3%ADo%20Lotes%20de%20Facturas&utm_medium=email&utm_campaign=AREA%20CLIENTE

The result should be 9 zips, but downloads fails

Thank you!

EDIT: DUplicate.

**Comment by jrie** [comment]
Do you have to be registered on this page, in order to see the downloads?

The page simply gives an error.

**Comment by marklieberman** [comment]
Refactor may have solved this. Please create a new issue after the new version is released in a couple days if you still have a problenm
