### ISSUE TITLE
Does nothing 

### ISSUE THREAD

**Issue by snhirsch** [marklieberman/downloadstar#15]
Title says it.  I must be missing something here.  After highlighting all files to be downloaded, I specify a directory and push the green button.  Absolutely nothing happens.

This is on Ubuntu 16.04 running Firefox 57.0.3

**Comment by benninkcorien** [comment]
Same problem on Windows 10.
Hit the blue download button, nothing happens.

**Comment by benninkcorien** [comment]
Edit: Change the path to "DownloadStar/" and it does work. (path is a subfolder of default download destinatino?)

**Comment by jrie** [comment]
I would assume it's not about the path, from my knowledge, and I used the addon to store downloads in other directories.

Can you point to the URL where the problem occured, where nothing happend?

**Comment by snhirsch** [comment]
Any and all source URLs show the problem.  After a bit of experimentation, it seems that DownloadStar accepts only _relative_ paths and assumes them to be normal to my home directory.  If that's a deliberate design choice, so be it, but it should be documented clearly AND the code should disallow leading slashes in the "Download To" field.

**Comment by jrie** [comment]
If I understand right, there is no permission to store data, from the browser, outside the home directory, this might be desired. But I am not sure.

On the other hand, replacing ".././././folder" should be fine, I would guess.

Maybe the second statement, just, should be filtered on input?

**Comment by marklieberman** [comment]
@snhirsch Web extensions are only allowed to make downloads inside the default downloads folder. The downloads API will reject any path outside of the download directory. Best I can do is add a tooltip or something.

**Comment by snhirsch** [comment]
Again:  I have no argument with the functionality or limits on placement.  But, if it is not possible to enter anything but paths relative to Downloads directory, then the extension simply should not accept a leading slash.  To allow that and quietly do nothing at all is just not reasonable user interface design.  

A hover-triggered tooltip would also be a good idea.
