### ISSUE TITLE
Unable to download base64 images

### ISSUE THREAD

**Issue by shoval** [marklieberman/downloadstar#18]
Working with Jupyter, I encounter many images that are loaded into the page using a base64 source (as opposed to a web address source). Download Star recognizes these as images and allows marking and filtering them (see screenshot), but clicking 'Download' does nothing. Downloading the web-sourced images on the page does work.

![download_star_base64](https://user-images.githubusercontent.com/1183305/37894637-7ed74800-30e7-11e8-9525-60f96e9fd4a2.png)

**Comment by marklieberman** [comment]
Fixed by 9e8c7b80ceb386891992ab26853850156d8679f1
