### ISSUE TITLE
Make localizable

### ISSUE THREAD

**Issue by MikkCZ** [marklieberman/downloadstar#2]
I do not see any l10n files here.

**Comment by marklieberman** [comment]
I'll look into making it localizable.

**Comment by MikkCZ** [comment]
@marklieberman What is the current status? If you haven't started working on it yet, I may have a look during this or the next week.

**Comment by marklieberman** [comment]
@MikkCZ I haven't started it yet. I had planned to get the next release of Foxy Gestures out and then switch development focus to Download Star for a while. Unfortunately, my house caught fire on Monday and I can't go home for a while, so development may be slow for a while depending on my circumstances.

**Comment by MikkCZ** [comment]
Oh, I am sorry to hear that.

I will look at this issue during the coming week.
