### ISSUE TITLE
URL encoded filenames are not URL decoded

### ISSUE THREAD

**Issue by martincampbell** [marklieberman/downloadstar#23]
I am using Download Star 1.0.1 in Firefox 60.0 on macOS High Sierra 10.13.4.
When I download URL encoded filenames (e.g. containing %20 instead of space), the filename is not URL decoded.
Enhancement Request: Would it be possible to URL decode URL encoded filenames?

**Comment by OkanEsen** [comment]
This was definitely fixed in this commit 8593fca4e2c070b5dae77a649d55baf91efeaf5b but the newest state isn't on par with AMO.

Once @marklieberman pushes the new version to AMO this can be closed.

**Comment by marklieberman** [comment]
New release is being pushed to AMO shortly.
