### ISSUE TITLE
downloading from bandcamp does not extract filenames - numerical file IDs only

### ISSUE THREAD

**Issue by teletrail** [marklieberman/downloadstar#28]
as explained in title, when I attempt to download using your manager files end up being named liek this:
![screenshot_20180602_205901](https://user-images.githubusercontent.com/27707208/40872749-cceb54d2-66a7-11e8-8e58-4c4a63af6d2c.png)

using quantum nightly, but I think the problem existed with stable.

would be great if this works, bulk downloads off bandcamp are  my main use for the addon.

thanks!

**Comment by marklieberman** [comment]
Probably will be resolved by implementing #27, but can you link me an example page so I can see the page source?

**Comment by teletrail** [comment]
https://bandcamp.com/download?from=receipt&payment_id=2386628815&sig=a0ad8ebf581a82d29cea2918af5d84e0

hope this is useful?
