### ISSUE TITLE
Batch Downloads

### ISSUE THREAD

**Issue by bup4gr** [marklieberman/downloadstar#30]
Add batch dowload like https://www.downthemall.net/howto/help/english-menu/batch-downloadsbatch-descriptors/ to download star

**Comment by OkanEsen** [comment]
Same opinion as: https://github.com/marklieberman/downloadstar/issues/31#issuecomment-399773180

**Comment by bup4gr** [comment]
The download in external download manager does not work in all sites that use identification through cookies or javascript sessions do not work in external download manager (like in https://github.com/marklieberman/downloadstar/issues/31).

For example:
- external download manager does not work;
- in every page there is a different link to a pdf (in page n. 1 there is link www.site.com/1.pdf; in page n. 2 there is www.site.com/2.pdf; ...)
If download star support batch download you can download all links in few seconds
If download star do NOT support batch download you have to manually download every single link using hours or days

**Comment by marklieberman** [comment]
This issue is basically the same as #6 in that the main feature is batch descriptors. Closing as duplicate for now. I will look into some type of batch descriptor feature, but it will not be implemented in quite the way that DtA did it.
