### ISSUE TITLE
Queue size limit should not apply to new items in queue

### ISSUE THREAD

**Issue by derfasthirnlosenick** [marklieberman/downloadstar#39]
While the scraping accepts >1,000 links, the downloads themselves stop after hitting 1,000.

Is there a technical reason why the queue is limited to 1,000 items (download.js, line 325)?
If not, would it be possible to increase to, e.g. 500,000?

**Comment by marklieberman** [comment]
The queue isn't exposed yet, so its all under the hood. I needed to cap it to ensure it doesn't grow without limit and eat a bunch of memory. I didn't think anyone would add 1000+ files in one shot.
