### ISSUE TITLE
You totally just screwed up this add-on.  It was working fine for me but now it doesn't work at all, thanks.  Why do you "fix" things that aren't broke?

### ISSUE THREAD

**Issue by noxomus** [marklieberman/downloadstar#40]

**Comment by marklieberman** [comment]
works fine on all my machines. why don't you try using your words to explain the problem or just install the old version from AMO.

**Comment by noxomus** [comment]
ok, if you were to go to 4chan and try downloading a thread, now it will only download the thumbnail and not the actual picture. Sorry if i am coming off rude, I just hate that software developers change things for no apparent reason and further limits the functionality of the product.

**Comment by marklieberman** [comment]
I use it on 4chan all the time. make sure the chain-link icon in the bottom left is clicked on. you want it to scrape links, not embeds. you should see the file urls are that ones that do not end with "s"

**Comment by marklieberman** [comment]
So, did that solve your problem or are you gonna leave me in suspense?

**Comment by noxomus** [comment]
My apologies Mark, it works fine.
thank you very much for your time.

nox
