### ISSUE TITLE
Downloaded broken images on pixiv.net since there is no referrer.

### ISSUE THREAD

**Issue by thelastfantasy** [marklieberman/downloadstar#46]
Sample page: [https://www.pixiv.net/member_illust.php?id=27932472](https://www.pixiv.net/member_illust.php?id=27932472)
I download images with this userscript: [https://greasyfork.org/zh-CN/scripts/24252-%E4%BB%99%E5%B0%8Apixiv%E5%9B%BE%E7%89%87%E4%B8%8B%E8%BD%BD%E5%99%A8](https://greasyfork.org/zh-CN/scripts/24252-%E4%BB%99%E5%B0%8Apixiv%E5%9B%BE%E7%89%87%E4%B8%8B%E8%BD%BD%E5%99%A8)

You can also check: [https://bugzilla.mozilla.org/show_bug.cgi?id=1367626](https://bugzilla.mozilla.org/show_bug.cgi?id=1367626)

**Comment by marklieberman** [comment]
Appears to have been fixed in FF70. If it is not working, please reply and I will re-open.
