### ISSUE TITLE
Remember link selection till downloaded or discarded

### ISSUE THREAD

**Issue by kamizoli** [marklieberman/downloadstar#54]
I don't know if the Firefox apis allow it, but I would like downloadstar to remember the download link selection for a webpage till downloaded. As the downloadstar windows does not stay open, when one has to leave firefox while in the process of choosing files, on coming back one has to do the selection again. 
Downloadstar will remeber the filter selection, but not the invidual chosen download links. 
If the downloadstar pup-up could stay open, it would help or a selection would be saved internally for a while. Another solution might be to "export" the downloadstar pop-up and the selection to a tab.

One other thing, I like the preview images and the information displayed in downloadstar, but sometimes I whish I could toggle to a more compact view, even without preview images, just one line per link.
I guess it is not possible to adjust the size of the downloadstar window to show more links instead?

**Comment by marklieberman** [comment]
I haven't had any time to work on DS lately, but when I do I will keep these things in mind. A more compact view is definitely a feature I will implement.
