### ISSUE TITLE
Include links from CSS

### ISSUE THREAD

**Issue by martin-rueegg** [marklieberman/downloadstar#66]
Currently, background images are not shown in the list. CSS (in files or inline with the `style` attribute) should be scanned too.

```<div style="background-image: url(&quot;https://example.com/some/image.jpg&quot;); background-position: 50% 50%; background-size: auto 100%;"></div>```

Version: 2.0.2

**Comment by OkanEsen** [comment]
This should already work via  "Show media from plain-text".
