### ISSUE TITLE
Use naming mask in download paths didn't work?

### ISSUE THREAD

**Issue by plokkicz** [marklieberman/downloadstar#68]
I have DownloadStar 2.0.2
Firefox 65.0.1 64-bit
Win7 64

[Use naming mask in download paths #63](https://github.com/marklieberman/downloadstar/pull/63)
When i use naming mask in pathname "${tabUrl[hostname]}" (or any other) my download folder is named "${tabUrl[hostname]}". Naming mask in filenames "${text}" works perfectly. Its only my problem?
thx

**Comment by tigregalis** [comment]
The current source version hasn't been built and distributed. You can clone/download the repo, `npm install` it, then run it as a temporary add-on, but that's the only way I know how to do it.
