### ISSUE TITLE
Download fails if I'm authenticated

### ISSUE THREAD

**Issue by pandronic** [marklieberman/downloadstar#72]
I download invoices every months from a CMS. They are all linked in a page a have an URL similar to this: http://example.com/invoices/invoice_number.pdf

The PDFs are generated on the fly. The CMS first checks if the user is authenticated (by checking a variable in the current session) and then returns the document. If the user is not authenticated it triggers a redirect to the login page.

This worked fine last time I tried (end of April). Now Download Star returns the login page, not the PDF (as if the user is not logged in)

I changed the requirement in the invoice generating script for the user to be logged in and Download Star works again, but obviously I don't want to leave it like this.

Using latest version of Firefox (67.0.1) and Download Star (2.0.2)

**Comment by ngg71** [comment]
I have exactly the same issue. Was working a few weeks ago and now downloads the login page .

**Comment by pandronic** [comment]
So, I did a little bit of testing. Things work as usual in Firefox 66.0.4, so something happened in Firefox 67.

**Comment by emcmurray** [comment]
It's likely related to the changes to prevent third party cookies from tracking changes that occurred in version 67
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Storage_access_policy

**Comment by emcmurray** [comment]
For people who need an immediate solution - the ESR version of firefox will still allow you to work with download star and pages that require cookies. https://www.mozilla.org/en-US/firefox/organizations/

Reading through, I think that if  permissions manifest gets updated to include cookies, that download star might be able to work again.... 
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies
https://github.com/mdn/webextensions-examples/blob/master/cookie-bg-picker/manifest.json <-the current manifest doesn't include cookies like this one does.

**Comment by byteit101** [comment]
At least on linux, 60.7.1esr doesn't correctly send cookies either

**Comment by byteit101** [comment]
Might be a Fx bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1561654

I tried adding the cookies permission and it didn't solve it. 
A minimal rack server I used to test this: https://gist.github.com/byteit101/2750e81d10a22f7c0b2ad8290c894139

**Comment by pandronic** [comment]
The problem was fixed by Fx 69. Nice.
